### ISSUE TITLE
No Macro Compendium 

### ISSUE THREAD

**Issue by SoilentBrad** [reyzor1991/pf2e-macros#1]
Hi! I was hoping to be able to use this for my monk player. But there’s no compendium of the macros you’ve made. I tried copying the code of the flurry of blows into a new macro, and it did nothing. 

Is there something I’m missing? Is it something you forgot to add? I’d really like to get flurry of blows working.

**Comment by reyzor1991** [comment]
New world - add pf2e macros

<img width="299" alt="Screenshot 2024-07-19 at 19 11 09" src="https://github.com/user-attachments/assets/a864feb0-8f89-4967-94ea-c2a5e06ee2c0">

<img width="291" alt="Screenshot 2024-07-19 at 19 11 53" src="https://github.com/user-attachments/assets/1c072ec3-95ed-40f4-8d76-8025a54f6cf3">

**Comment by reyzor1991** [comment]
When you search, is it exists?

<img width="315" alt="Screenshot 2024-07-19 at 19 14 30" src="https://github.com/user-attachments/assets/9d59a1bc-940b-4953-94cf-698a7c2ec2d3">

**Comment by reyzor1991** [comment]
any errors?

**Comment by SoilentBrad** [comment]
Thank you very much for that. I don't know how I looked past it. Maybe I wasn't looking for a folder. It works perfectly! Sorry for opening the unnecessary issue.
