### ISSUE TITLE
Flurry of blows doesn't apply forceful trait of second blow

### ISSUE THREAD

**Issue by fortypercenttitanium** [reyzor1991/pf2e-macros#10]
If both attacks in a flurry are the same attack, have the forceful trait, and both hit, a circumstance bonus should be applied to the second damage roll equal to the number of damage dice of that damage roll.

![image](https://github.com/user-attachments/assets/154f2a06-d899-44d3-8ed3-1acb3c94083a)

![image](https://github.com/user-attachments/assets/aecddf3d-5903-495a-8fda-18c234e24cf7)

**Comment by reyzor1991** [comment]
For right now it's impossible to apply forceful bonus via macro, because forceful bonus is ignored and not predicated by system by default.
So only with manual rolling it's possible to apply forceful bonus
