### ISSUE TITLE
Twin Feint 2 issues

### ISSUE THREAD

**Issue by bsleys** [reyzor1991/pf2e-macros#4]
Twin Feint isn't applying MAP to the second attack the last sentence of Twin Feint states "Apply your multiple attack penalty to the Strikes normally."

Second the damage of both attacks is combined, assuming they both hit.  Nothing in Twin Feint states the damage is combined which can lead to issues when dealing with resistance and vulnerabilities.

For reference the full text of Twin Feint is as follows:
Requirements You are wielding two melee weapons, each in a different hand.

You use an attack with one weapon to distract your foe from a second attack coming at a different angle. Make one Strike with each of your two melee weapons, both against the same target. The target is automatically Off-Guard against the second attack. Apply your multiple attack penalty to the Strikes normally.

**Comment by bsleys** [comment]
Thanks for the quick turnaround. However it still looks like both damages are combined into one damage to be applied to the target.

**Comment by reyzor1991** [comment]
Damages always combined

**Comment by reyzor1991** [comment]
It's logic of macros
