### ISSUE TITLE
Target is off-guard is not working

### ISSUE THREAD

**Issue by JornieNonsubia** [reyzor1991/pf2e-macros#5]
I checked it as GM

Select your token
Target enemy
press macro

Nothing happens, in console this appear
![image](https://github.com/user-attachments/assets/3ccc7dee-4b33-4490-8ed0-e8b9ce7af460)

**Comment by JornieNonsubia** [comment]
To be more precise this line of code
![image](https://github.com/user-attachments/assets/b2186638-9391-4310-b918-1a9d6f94f168)

Дякую за працю)

**Comment by reyzor1991** [comment]
Fixed, re import/added macro
