### ISSUE TITLE
Twin Takedown doesn't account for `twin` weapon trait when calculating damage

### ISSUE THREAD

**Issue by martosaur** [reyzor1991/pf2e-macros#7]
With Prey for Death adventure having two Sawtooth Sabers suddenly became very common, so it'd be nice to have [`twin`](https://2e.aonprd.com/Traits.aspx?ID=717)trait working in Twin Takedown macro.

**Comment by reyzor1991** [comment]
This logic could cover by module, but only if you not use feature like auto roll from workbecnh or need additional logic not related to macros

**Comment by martosaur** [comment]
I don't think we use auto roll or anything special to roll damage, although I'm a player and don't deal much with Foundry setup. So yeah, ultimately your call if you want to implement this or not, but let me know if you need any input from me!

**Comment by reyzor1991** [comment]
Next release
